Adding release github action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,76 +14,42 @@
 # limitations under the License.
 #
 name: Elyra Build and Release
-
 on:
+  push:
+    tags:
+      - v*
   workflow_dispatch:
-    inputs:
-      version:
-        description: 'Version number for the release'
-        required: true
-      branch:
-        description: 'Branch to release from'
-        required: true
-
 jobs:
-  build:
-    uses: ./.github/workflows/build.yml
-
   release:
+    name: Release
     runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+    env:
+      FORCE_COLOR: "1"
     steps:
-      - name: Checkout code
+      - name: Check out the repository
         uses: actions/checkout@v4
-
+        with:
+          fetch-depth: 0
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.11'
-
-      - name: Create release branch
+          python-version: "3.11"
+      - name: Check version
         run: |
-          git checkout -b rel-${{ github.event.inputs.version }} ${{ github.event.inputs.branch }}
-          git push -u origin rel-${{ github.event.inputs.version }}
-
-      - name: Update version file
-        run: |
-          # edits the version file in place
-          sed -i '' 's/^__version__ = ".*"/__version__ = "${{ github.event.inputs.version }}"/' elyra/_version.py
-          git config user.name "Edson Tirelli"
-          git config user.email ed.tirelli@github.com
-          git commit -m "Bump version to ${{ github.event.inputs.version }}" elyra/_version.py
-          git push
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install twine
-
+          set -o pipefail
+          LATEST_TAG=$(git describe --tags --match="v*")
+          if [[ "$LATEST_TAG" =~ $(cat ./elyra/_version.py | grep "__version__" | cut -d'"' -f 2) ]]; then
+            echo "::error title='$LATEST_TAG tag does not match project version'::"
+            exit 1
+          fi
       - name: Build package
-        run: make install
-
-#      - name: Release to PyPI
-#        env:
-#          TWINE_USERNAME: __token__
-#          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
-#        run: |
-#          twine upload dist/*
-
-      - name: Create tag
-        if: success()
         run: |
-          git tag v${{ github.event.inputs.version }}
-          git push origin v${{ github.event.inputs.version }}
-
-#      - name: Create GitHub Release
-#        uses: actions/create-release@v1
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#        with:
-#          tag_name: v${{ github.event.inputs.version }}
-#          release_name: Release ${{ github.event.inputs.version }}
-#          body: |
-#            Release version ${{ github.event.inputs.version }}
-#          draft: false
-#          prerelease: false
-
+          make install
+      - name: Publish package on PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          verbose: true
+          print-hash: true
+          packages-dir: dist/
